# code: language=ansible
---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    ## テストの前処理
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Gather service facts
      ansible.builtin.service_facts:
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
      become: true
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | sort | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | sort | list }}"
    ## SpamAssassinパッケージのテスト
    - name: Assert SpamAssassin package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['spamassassin'] is defined
        fail_msg: "SpamAssassin package is not installed"
        success_msg: "SpamAssassin package is installed"
    ## ユーザーのテスト
    - name: Get user facts
      ansible.builtin.getent:
        database: passwd
        key: mailpit
    - name: Assert user
      ansible.builtin.assert:
        that:
          - getent_passwd['mailpit'] is defined
        fail_msg: "mailpit user does not exist"
        success_msg: "mailpit user exists"
    ## グループのテスト
    - name: Get group facts
      ansible.builtin.getent:
        database: group
        key: mailpit
    - name: Assert group
      ansible.builtin.assert:
        that:
          - getent_group['mailpit'] is defined
        fail_msg: "mailpit group does not exist"
        success_msg: "mailpit group exists"
    ## ファイルのテスト
    - name: Test files
      block:
        - name: Check installed mailpit
          ansible.builtin.stat:
            path: /usr/local/bin/mailpit
          register: mailpit_bin_result
        - name: Assert mailpit binary
          ansible.builtin.assert:
            that:
              - mailpit_bin_result.stat.exists
              - mailpit_bin_result.stat.executable
            fail_msg: "mailpit binary is not properly installed"
            success_msg: "mailpit binary is properly installed"
        - name: Check mailpit config directory
          ansible.builtin.stat:
            path: /etc/mailpit
          register: mailpit_config_dir_result
        - name: Assert mailpit config directory
          ansible.builtin.assert:
            that:
              - mailpit_config_dir_result.stat.exists
              - mailpit_config_dir_result.stat.pw_name == 'mailpit'
              - mailpit_config_dir_result.stat.gr_name == 'mailpit'
              - mailpit_config_dir_result.stat.mode == '0755'
            fail_msg: "mailpit config directory is not properly configured"
            success_msg: "mailpit config directory is properly configured"
        - name: Check mailpit environment file
          ansible.builtin.stat:
            path: /etc/default/mailpit
          register: mailpit_env_file_result
        - name: Assert mailpit env file
          ansible.builtin.assert:
            that:
              - mailpit_env_file_result.stat.exists
            fail_msg: "mailpit environment file not found"
            success_msg: "mailpit environment file exists"
        - name: Check mailpit SpamAssassin configuration
          ansible.builtin.lineinfile:
            path: /etc/default/mailpit
            line: 'MP_ENABLE_SPAMASSASSIN="localhost:783"'
          check_mode: true
          register: mailpit_spamassassin_cfg_result
        - name: Assert mailpit SpamAssassin configuration
          ansible.builtin.assert:
            that:
              - mailpit_spamassassin_cfg_result is not changed
            fail_msg: "mailpit SpamAssassin configuration is not properly set"
            success_msg: "mailpit SpamAssassin configuration is properly set"
        - name: Check mailpit systemd unit file
          ansible.builtin.stat:
            path: /usr/lib/systemd/system/mailpit.service
          register: mailpit_systemd_unit_file_result
        - name: Assert mailpit systemd unit file
          ansible.builtin.assert:
            that:
              - mailpit_systemd_unit_file_result.stat.exists
            fail_msg: "mailpit systemd unit file not found"
            success_msg: "mailpit systemd unit file exists"
    ## サービスのテスト
    - name: Assert SpamAssassin service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['spamd.service'] is defined
          - ansible_facts.services['spamd.service']['state'] == 'running'
          - ansible_facts.services['spamd.service']['status'] == 'enabled'
        fail_msg: "SpamAssassin (spamd) service is not running or not enabled"
        success_msg: "SpamAssassin (spamd) service is running and enabled"
    - name: Assert mailpit service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['mailpit.service'] is defined
          - ansible_facts.services['mailpit.service']['state'] == 'running'
          - ansible_facts.services['mailpit.service']['status'] == 'enabled'
        fail_msg: "mailpit service is not running or not enabled"
        success_msg: "mailpit service is running and enabled"
    ## 待受ポートのテスト
    - name: Assert SpamAssassin listening port
      ansible.builtin.assert:
        that:
          - 783 in listen_tcp_posts
        fail_msg: "SpamAssassin is not listening on port 783"
        success_msg: "SpamAssassin is listening on port 783"
    - name: Assert mailpit listening ports
      ansible.builtin.assert:
        that:
          - 1025 in listen_tcp_posts
          - 8025 in listen_tcp_posts
        fail_msg: "mailpit is not listening on required ports (1025, 8025)"
        success_msg: "mailpit is listening on required ports"
    ## APIのテスト
    - name: Send test mail
      community.general.mail:
        subject: test mail subject
        to: test to <to@example.com>
        from: test from <from@example.com>
        body: test mail body
        port: 1025
    - name: Test API mailpit information request
      ansible.builtin.uri:
        url: http://localhost:8025/api/v1/info
      register: mailpit_api_result
    - name: Assert API info endpoint
      ansible.builtin.assert:
        that: mailpit_api_result.status == 200
        fail_msg: "mailpit API info endpoint did not return 200"
        success_msg: "mailpit API info endpoint is working"
    - name: Test API List message request
      ansible.builtin.uri:
        url: http://localhost:8025/api/v1/messages
      register: mailpit_list_message_api_result
    - name: Assert API messages endpoint
      ansible.builtin.assert:
        that:
          - mailpit_list_message_api_result.status == 200
          - mailpit_list_message_api_result.json.messages[0].Subject == "test mail subject"
          - mailpit_list_message_api_result.json.messages[0].From.Address == "from@example.com"
          - mailpit_list_message_api_result.json.messages[0].From.Name == "test from"
          - mailpit_list_message_api_result.json.messages[0].To[0].Address == "to@example.com"
          - mailpit_list_message_api_result.json.messages[0].To[0].Name == "test to"
        fail_msg: "mailpit did not properly receive and store the test mail"
        success_msg: "mailpit properly received and stored the test mail"
